id: IED4C0BE6
legacy_id: P007839
ocr_import_info:
  bdrc_scan_id: W23379
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T14:30:28'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:02:18.428271+00:00'
last_modified: 2022-09-02 09:02:28.837384
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23379
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23379
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྡོམ་གསུམ་བསྟན་པའི་སྒྲོན་མེ།
  author: རིག་འཛིན་ཀུན་བཟང་ཤེས་རབ།
statistics:
  ocr_word_mean_confidence_index: 0.6531534416708369
  ocr_word_median_confidence_index: 0.7799999713897705
quality: null
bases:
  I1562:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1562
      total_pages: 244
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1562.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.6531534416708369
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
