id: P007839
initial_creation_type: ocr
source_metadata:
  id: bdr:W23379
  title: སྡོམ་གསུམ་བསྟན་པའི་སྒྲོན་མེ
  author: ''
  volumes:
    d6e8ce2976b744f194e2ab2836ce0311:
      image_group_id: I1562
      title: ''
      volume_number: 1
      total_pages: 244
ebook_metadata:
  title: སྡོམ་གསུམ་བསྟན་པའི་སྒྲོན་མེ
  author: ''
  sku: P007839
  cover: cover.jpg
  layers:
  - pagination
